"""Integral structures for finitely generated rational isometry groups.

The public objects in this module retain preamble lattices, embeddings, and
isometries.  Sage matrices are used only privately to normalize a finite
``ZZ``-span inside a rational vector space.
"""

from __future__ import annotations

from functools import cached_property

from dzack_research.preamble.all import FreeModule, module_embedding
from dzack_research.preamble.categories._lattice import Lattice
from dzack_research.preamble.categories.lattice_morphisms import LatticeIsometry
from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
    ModuleEmbedding,
    module_coefficients,
)
from sage.matrix.constructor import matrix
from sage.rings.integer_ring import ZZ as SageZZ
from sage.rings.rational_field import QQ as SageQQ
from sage.structure.sage_object import SageObject


class RationalMatrixGroup(SageObject):
    """A finitely generated rational isometry group on one preamble lattice.

    The selected generators are actual elements of ``V.Aut()``.  No raw matrix
    is part of the public representation; matrix lowering belongs to private
    computation seams such as the finite integral-structure action below.
    """

    def __init__(
        self,
        rational_lattice: Lattice,
        generators: tuple[LatticeIsometry, ...],
    ) -> None:
        selected = tuple(generators)
        automorphisms = rational_lattice.Aut()
        match any(generator.parent() is not automorphisms for generator in selected):
            case True:
                raise ValueError("rational-group generators must be automorphisms of one lattice")
            case False:
                pass
        self._rational_lattice = rational_lattice
        self._generators = selected

    def rational_lattice(self) -> Lattice:
        """Return the rational lattice acted on by this group."""
        return self._rational_lattice

    def generators(self) -> tuple[LatticeIsometry, ...]:
        """Return the selected live isometry generators."""
        return self._generators

    def generators_and_inverses(self) -> tuple[LatticeIsometry, ...]:
        """Return the selected generators and their inverses."""
        return self._generators + tuple(~generator for generator in self._generators)

    def _repr_(self) -> str:
        return f"Rational isometry group on {self.rational_lattice()} generated by {len(self.generators())} elements"


def _embedded_basis(inclusion: ModuleEmbedding):
    domain = inclusion.domain()
    return tuple(inclusion(generator) for generator in domain.module_generators())


def _underlying_coordinates(space, element):
    ambient = space.module_over_extension()
    underlying = space(element).underlying_element()
    coefficients = module_coefficients(underlying, ambient)
    return tuple(
        SageQQ(coefficients.get(label, ambient.base_ring().zero()))
        for label in ambient.module_generating_set()
    )


def _span_embedding(space, elements) -> ModuleEmbedding:
    """Return the exact ``ZZ``-span of finitely many elements of ``Res(V)``."""
    elements = tuple(elements)
    match elements:
        case ():
            raise ValueError("an integral lattice span requires at least one generator")
        case _:
            pass

    rows = tuple(_underlying_coordinates(space, element) for element in elements)
    denominator = SageZZ.one()
    for row in rows:
        for entry in row:
            denominator = denominator.lcm(entry.denominator())
    integral_rows = tuple(
        tuple(SageZZ(denominator * entry) for entry in row)
        for row in rows
    )
    integer_span = matrix(SageZZ, integral_rows).row_module()
    basis = integer_span.basis_matrix()

    ambient = space.module_over_extension()
    ambient_labels = tuple(ambient.module_generating_set())
    domain = FreeModule(SageZZ, basis.nrows())

    def image(position):
        row = basis[int(position)]
        coefficients = {}
        for column, label in enumerate(ambient_labels):
            match row[column] == 0:
                case True:
                    pass
                case False:
                    coefficients[label] = ambient.base_ring()(
                        SageQQ(row[column]) / denominator
                    )
        return space.wrap(ambient.linear_combination(coefficients))

    return module_embedding(
        domain,
        space,
        {label: image(label) for label in domain.module_generating_set()},
    )


def _same_embedded_lattice(left: ModuleEmbedding, right: ModuleEmbedding) -> bool:
    match left.codomain() is right.codomain():
        case False:
            return False
        case True:
            pass
    try:
        left.factor_through(right)
        right.factor_through(left)
    except ValueError:
        return False
    return True


class IntegralStructureAction(SageObject):
    """A rational group acting on lattices commensurable with one selected lattice.

    ``lattice_inclusion`` is the actual monomorphism ``L -> Res_Z^Q(V)``.  The
    invariant-overlattice procedure has the explicit precondition from the
    source algorithm: the selected rational group stabilizes some lattice
    commensurable with ``L``.  Under that hypothesis the ascending sequence of
    finite ``ZZ``-spans stabilizes.
    """

    def __init__(
        self,
        rational_group: RationalMatrixGroup,
        lattice_inclusion: ModuleEmbedding,
    ) -> None:
        space = lattice_inclusion.codomain()
        match space.module_over_extension() is rational_group.rational_lattice():
            case False:
                raise ValueError("the integral structure must lie in the rational group's space")
            case True:
                pass
        match lattice_inclusion.domain().base_ring() is space.base_ring():
            case False:
                raise ValueError("the lattice and restricted rational space require one base ring")
            case True:
                pass
        self._rational_group = rational_group
        self._lattice_inclusion = lattice_inclusion

    def rational_group(self) -> RationalMatrixGroup:
        return self._rational_group

    def lattice_inclusion(self) -> ModuleEmbedding:
        """Return the selected lattice embedding ``L -> Res(V)``."""
        return self._lattice_inclusion

    @cached_property
    def _invariant_overlattice(self):
        current = self.lattice_inclusion()
        space = current.codomain()
        while True:
            current_basis = _embedded_basis(current)
            spanning = list(current_basis)
            for generator in self.rational_group().generators_and_inverses():
                spanning.extend(
                    space.wrap(generator(vector.underlying_element()))
                    for vector in current_basis
                )
            enlarged = _span_embedding(space, spanning)
            match _same_embedded_lattice(current, enlarged):
                case True:
                    return current
                case False:
                    current = enlarged

    def invariant_overlattice(self) -> ModuleEmbedding:
        """Return the smallest represented over-lattice stable under the generators.

        This is the source operation ``MatrixIntegral_GetInvariantSpace``:
        repeatedly take the ``ZZ``-span of the current lattice and all generator
        and inverse images.  No saturation is taken inside the divisible
        rational ambient space.
        """
        return self._invariant_overlattice

    @cached_property
    def _quotient_exponent(self):
        original = self.lattice_inclusion()
        invariant = self.invariant_overlattice()
        into_invariant = original.factor_through(invariant)
        return into_invariant.cokernel().exponent()

    def quotient_exponent(self):
        """Return the exponent of ``M/L`` for ``M`` the invariant over-lattice."""
        return self._quotient_exponent

    def _repr_(self) -> str:
        return f"Integral-structure action of {self.rational_group()} on {self.lattice_inclusion().domain()}"


__all__ = ["IntegralStructureAction", "RationalMatrixGroup"]
