"""Integral structures for finitely generated rational isometry groups.

The public objects in this module retain preamble lattices, embeddings, and
isometries.  Sage matrices are used only privately to normalize a finite
``ZZ``-span inside a rational vector space.
"""

from __future__ import annotations

from functools import cached_property

from dzack_research.preamble.all import FreeModule, module_embedding
from dzack_research.preamble.categories._lattice import Lattice
from dzack_research.preamble.categories.lattice_morphisms import LatticeIsometry
from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
    ModuleEmbedding,
    module_coefficients,
)
from sage.libs.gap.libgap import libgap
from sage.matrix.constructor import matrix
from sage.rings.integer_ring import ZZ as SageZZ
from sage.rings.rational_field import QQ as SageQQ
from sage.structure.sage_object import SageObject


class RationalMatrixGroup(SageObject):
    """A finitely generated rational isometry group on one preamble lattice.

    The selected generators are actual elements of ``V.Aut()``.  No raw matrix
    is part of the public representation; matrix lowering belongs to private
    computation seams such as the finite integral-structure action below.
    """

    def __init__(
        self,
        rational_lattice: Lattice,
        generators: tuple[LatticeIsometry, ...],
    ) -> None:
        selected = tuple(generators)
        automorphisms = rational_lattice.Aut()
        match any(generator.parent() is not automorphisms for generator in selected):
            case True:
                raise ValueError("rational-group generators must be automorphisms of one lattice")
            case False:
                pass
        self._rational_lattice = rational_lattice
        self._generators = selected

    def rational_lattice(self) -> Lattice:
        """Return the rational lattice acted on by this group."""
        return self._rational_lattice

    def generators(self) -> tuple[LatticeIsometry, ...]:
        """Return the selected live isometry generators."""
        return self._generators

    def generators_and_inverses(self) -> tuple[LatticeIsometry, ...]:
        """Return the selected generators and their inverses."""
        return self._generators + tuple(~generator for generator in self._generators)

    def _repr_(self) -> str:
        return f"Rational isometry group on {self.rational_lattice()} generated by {len(self.generators())} elements"


def _embedded_basis(inclusion: ModuleEmbedding):
    domain = inclusion.domain()
    return tuple(inclusion(generator) for generator in domain.module_generators())


def _underlying_coordinates(space, element):
    ambient = space.module_over_extension()
    underlying = space(element).underlying_element()
    coefficients = module_coefficients(underlying, ambient)
    return tuple(
        SageQQ(coefficients.get(label, ambient.base_ring().zero()))
        for label in ambient.module_generating_set()
    )


def _span_embedding(space, elements) -> ModuleEmbedding:
    """Return the exact ``ZZ``-span of finitely many elements of ``Res(V)``."""
    elements = tuple(elements)
    match elements:
        case ():
            raise ValueError("an integral lattice span requires at least one generator")
        case _:
            pass

    rows = tuple(_underlying_coordinates(space, element) for element in elements)
    denominator = SageZZ.one()
    for row in rows:
        for entry in row:
            denominator = denominator.lcm(entry.denominator())
    integral_rows = tuple(
        tuple(SageZZ(denominator * entry) for entry in row)
        for row in rows
    )
    integer_span = matrix(SageZZ, integral_rows).row_module()
    basis = integer_span.basis_matrix()

    ambient = space.module_over_extension()
    ambient_labels = tuple(ambient.module_generating_set())
    domain = FreeModule(SageZZ, basis.nrows())

    def image(position):
        row = basis[int(position)]
        coefficients = {}
        for column, label in enumerate(ambient_labels):
            match row[column] == 0:
                case True:
                    pass
                case False:
                    coefficients[label] = ambient.base_ring()(
                        SageQQ(row[column]) / denominator
                    )
        return space.wrap(ambient.linear_combination(coefficients))

    return module_embedding(
        domain,
        space,
        {label: image(label) for label in domain.module_generating_set()},
    )


def _same_embedded_lattice(left: ModuleEmbedding, right: ModuleEmbedding) -> bool:
    match left.codomain() is right.codomain():
        case False:
            return False
        case True:
            pass
    try:
        left.factor_through(right)
        right.factor_through(left)
    except ValueError:
        return False
    return True


class ArithmeticSubgroup(RationalMatrixGroup):
    """A generated arithmetic subgroup retaining its ambient rational group."""

    def __init__(
        self,
        supergroup: RationalMatrixGroup,
        generators: tuple[LatticeIsometry, ...],
    ) -> None:
        self._supergroup = supergroup
        super().__init__(supergroup.rational_lattice(), generators)

    def supergroup(self) -> RationalMatrixGroup:
        return self._supergroup


class RightCosetDecomposition(SageObject):
    """A finite decomposition ``G/H`` with the subgroup explicitly on the right."""

    def __init__(
        self,
        ambient_group: RationalMatrixGroup,
        right_subgroup: ArithmeticSubgroup,
        representatives: tuple[LatticeIsometry, ...],
    ) -> None:
        self._ambient_group = ambient_group
        self._right_subgroup = right_subgroup
        self._representatives = tuple(representatives)

    def ambient_group(self) -> RationalMatrixGroup:
        return self._ambient_group

    def right_subgroup(self) -> ArithmeticSubgroup:
        return self._right_subgroup

    def representatives(self) -> tuple[LatticeIsometry, ...]:
        return self._representatives

    def cardinality(self) -> int:
        return len(self._representatives)

    def _repr_(self) -> str:
        return f"Right-subgroup cosets {self.ambient_group()}/{self.right_subgroup()} with {self.cardinality()} representatives"


class DoubleCosetIntersection(SageObject):
    """Finite-image intersection data for one double coset ``V g H``."""

    def __init__(
        self,
        representative: LatticeIsometry,
        finite_image_order: int,
        double_coset_size: int,
    ) -> None:
        self._representative = representative
        self._finite_image_order = int(finite_image_order)
        self._double_coset_size = int(double_coset_size)

    def representative(self) -> LatticeIsometry:
        return self._representative

    def finite_image_order(self) -> int:
        return self._finite_image_order

    def double_coset_size(self) -> int:
        return self._double_coset_size


class DoubleCosetDecomposition(SageObject):
    """A finite decomposition ``V \ G / H`` retaining all three group sides."""

    def __init__(
        self,
        left_subgroup: ArithmeticSubgroup,
        ambient_group: RationalMatrixGroup,
        right_subgroup: ArithmeticSubgroup,
        representatives: tuple[LatticeIsometry, ...],
        intersections: tuple[DoubleCosetIntersection, ...],
        finite_ambient_order: int,
        finite_left_order: int,
        finite_right_order: int,
    ) -> None:
        self._left_subgroup = left_subgroup
        self._ambient_group = ambient_group
        self._right_subgroup = right_subgroup
        self._representatives = tuple(representatives)
        self._intersections = tuple(intersections)
        self._finite_ambient_order = int(finite_ambient_order)
        self._finite_left_order = int(finite_left_order)
        self._finite_right_order = int(finite_right_order)

    def left_subgroup(self) -> ArithmeticSubgroup:
        return self._left_subgroup

    def ambient_group(self) -> RationalMatrixGroup:
        return self._ambient_group

    def right_subgroup(self) -> ArithmeticSubgroup:
        return self._right_subgroup

    def representatives(self) -> tuple[LatticeIsometry, ...]:
        return self._representatives

    def intersections(self) -> tuple[DoubleCosetIntersection, ...]:
        return self._intersections

    def cardinality(self) -> int:
        return len(self._representatives)

    def finite_ambient_order(self) -> int:
        return self._finite_ambient_order

    def finite_left_order(self) -> int:
        return self._finite_left_order

    def finite_right_order(self) -> int:
        return self._finite_right_order

    def _repr_(self) -> str:
        return f"Double cosets {self.left_subgroup()} \ {self.ambient_group()} / {self.right_subgroup()} with {self.cardinality()} representatives"


class FiniteIntegralRepresentation(SageObject):
    """The finite action controlling the integral structures in one commensurability class.

    The public orbit consists of actual submodules of ``M/dM``.  libGAP owns
    the private permutation group and subgroup preimage calculation; every
    resulting free-group word is evaluated back in the selected live rational
    isometries before it crosses the public boundary.
    """

    def __init__(self, action: "IntegralStructureAction") -> None:
        self._action = action
        self._orbit, self._orbit_witnesses = self._compute_submodule_orbit()
        self._generator_permutations = self._compute_generator_permutations()
        self._free_group = libgap.FreeGroup(len(action.rational_group().generators()))
        self._permutation_group = libgap.Group(list(self._generator_permutations))
        self._homomorphism = libgap.GroupHomomorphismByImages(
            self._free_group,
            self._permutation_group,
            self._free_group.GeneratorsOfGroup(),
            list(self._generator_permutations),
        )

    def action(self) -> "IntegralStructureAction":
        return self._action

    def orbit(self):
        """Return the finite orbit of ``S=L/dM`` as represented submodules."""
        return tuple(self._orbit)

    def orbit_witnesses(self) -> tuple[LatticeIsometry, ...]:
        """Return live rational isometries carrying ``S`` to the orbit members."""
        return tuple(self._orbit_witnesses)

    def image_order(self) -> int:
        """Return the order of the finite permutation image."""
        return int(self._permutation_group.Size())

    @staticmethod
    def _same_submodule(left, right) -> bool:
        match left.inclusion().codomain() is right.inclusion().codomain():
            case False:
                return False
            case True:
                pass
        try:
            left.inclusion().factor_through(right.inclusion())
            right.inclusion().factor_through(left.inclusion())
        except ValueError:
            return False
        return True

    def _orbit_position(self, candidate) -> int | None:
        for position, member in enumerate(self._orbit):
            match self._same_submodule(candidate, member):
                case True:
                    return position
                case False:
                    pass
        return None

    @staticmethod
    def _image_submodule(automorphism, submodule):
        return (automorphism * submodule.inclusion()).image()

    def _compute_submodule_orbit(self):
        seed = self.action().selected_submodule()
        orbit = [seed]
        witnesses = [self.action().rational_group().rational_lattice().Aut().one()]
        steps = tuple(
            zip(
                self.action()._finite_generator_automorphisms_and_inverses(),
                self.action().rational_group().generators_and_inverses(),
                strict=True,
            )
        )
        frontier = [0]
        while frontier:
            source_position = frontier.pop()
            source = orbit[source_position]
            source_witness = witnesses[source_position]
            for finite_automorphism, rational_automorphism in steps:
                candidate = self._image_submodule(finite_automorphism, source)
                existing_position = None
                for position, member in enumerate(orbit):
                    match self._same_submodule(candidate, member):
                        case True:
                            existing_position = position
                            break
                        case False:
                            pass
                match existing_position:
                    case None:
                        orbit.append(candidate)
                        witnesses.append(rational_automorphism * source_witness)
                        frontier.append(len(orbit) - 1)
                    case _:
                        pass
        return orbit, witnesses

    def _compute_generator_permutations(self):
        permutations = []
        for automorphism in self.action()._finite_generator_automorphisms():
            images = []
            for member in self._orbit:
                image = self._image_submodule(automorphism, member)
                position = self._orbit_position(image)
                match position:
                    case None:
                        raise ArithmeticError("the finite-module generator left the computed orbit")
                    case _:
                        images.append(position + 1)
            permutations.append(libgap.PermList(images))
        return tuple(permutations)

    def _evaluate_free_word(self, word) -> LatticeIsometry:
        representation = tuple(int(entry) for entry in libgap.ExtRepOfObj(word).sage())
        generators = self.action().rational_group().generators()
        result = self.action().rational_group().rational_lattice().Aut().one()
        for position in range(0, len(representation), 2):
            generator = generators[representation[position] - 1]
            exponent = representation[position + 1]
            match exponent < 0:
                case True:
                    generator = ~generator
                    exponent = -exponent
                case False:
                    pass
            for _step in range(exponent):
                result = result * generator
        return result

    @cached_property
    def _lattice_stabilizer(self) -> ArithmeticSubgroup:
        point_stabilizer = libgap.Stabilizer(self._permutation_group, 1)
        preimage = libgap.PreImage(self._homomorphism, point_stabilizer)
        lifted = tuple(
            self._evaluate_free_word(word)
            for word in preimage.GeneratorsOfGroup()
        )
        match all(self.action().preserves_selected_lattice(generator) for generator in lifted):
            case False:
                raise ArithmeticError("a lifted finite stabilizer generator does not preserve the lattice")
            case True:
                pass
        return ArithmeticSubgroup(self.action().rational_group(), lifted)

    def lattice_stabilizer(self) -> ArithmeticSubgroup:
        """Return the exact preimage of the stabilizer of ``S=L/dM``."""
        return self._lattice_stabilizer

    def transporter_to(self, target_submodule):
        """Return a live rational isometry carrying ``S`` to ``target_submodule``."""
        position = self._orbit_position(target_submodule)
        match position:
            case None:
                return None
            case _:
                return self._orbit_witnesses[position]

    @cached_property
    def _right_cosets(self) -> RightCosetDecomposition:
        return RightCosetDecomposition(
            self.action().rational_group(),
            self.lattice_stabilizer(),
            tuple(self._orbit_witnesses),
        )

    def right_cosets(self) -> RightCosetDecomposition:
        """Return ``G/H`` where ``H`` is the selected lattice stabilizer."""
        return self._right_cosets

    def _permutation_of_rational_isometry(self, automorphism: LatticeIsometry):
        finite_automorphism = self.action()._finite_automorphism(automorphism)
        images = []
        for member in self._orbit:
            image = self._image_submodule(finite_automorphism, member)
            position = self._orbit_position(image)
            match position:
                case None:
                    raise ArithmeticError("a rational subgroup generator leaves the finite orbit")
                case _:
                    images.append(position + 1)
        permutation = libgap.PermList(images)
        match permutation in self._permutation_group:
            case False:
                raise ValueError("the selected arithmetic subgroup is not contained in the ambient rational group")
            case True:
                return permutation

    def double_cosets(self, left_subgroup: ArithmeticSubgroup) -> DoubleCosetDecomposition:
        """Return ``left_subgroup \ G / H`` in the finite integral representation."""
        match left_subgroup.supergroup() is self.action().rational_group():
            case False:
                raise ValueError("a double-coset left subgroup must lie in the selected rational group")
            case True:
                pass
        left_image = libgap.Subgroup(
            self._permutation_group,
            [
                self._permutation_of_rational_isometry(generator)
                for generator in left_subgroup.generators()
            ],
        )
        right_image = libgap.Stabilizer(self._permutation_group, 1)
        representatives = []
        intersections = []
        for double_coset in libgap.DoubleCosets(
            self._permutation_group,
            left_image,
            right_image,
        ):
            finite_representative = double_coset.Representative()
            word = libgap.PreImagesRepresentative(
                self._homomorphism,
                finite_representative,
            )
            match str(word) == "fail":
                case True:
                    raise ArithmeticError("a finite double-coset representative has no rational lift")
                case False:
                    pass
            representative = self._evaluate_free_word(word)
            double_coset_size = int(double_coset.Size())
            numerator = int(left_image.Size()) * int(right_image.Size())
            match numerator % double_coset_size:
                case 0:
                    intersection_order = numerator // double_coset_size
                case _:
                    raise ArithmeticError("the finite double-coset size violates the orbit-stabilizer formula")
            representatives.append(representative)
            intersections.append(
                DoubleCosetIntersection(
                    representative,
                    intersection_order,
                    double_coset_size,
                )
            )
        return DoubleCosetDecomposition(
            left_subgroup,
            self.action().rational_group(),
            self.lattice_stabilizer(),
            tuple(representatives),
            tuple(intersections),
            int(self._permutation_group.Size()),
            int(left_image.Size()),
            int(right_image.Size()),
        )


class IntegralStructureAction(SageObject):
    """A rational group acting on lattices commensurable with one selected lattice.

    ``lattice_inclusion`` is the actual monomorphism ``L -> Res_Z^Q(V)``.  The
    invariant-overlattice procedure has the explicit precondition from the
    source algorithm: the selected rational group stabilizes some lattice
    commensurable with ``L``.  Under that hypothesis the ascending sequence of
    finite ``ZZ``-spans stabilizes.
    """

    def __init__(
        self,
        rational_group: RationalMatrixGroup,
        lattice_inclusion: ModuleEmbedding,
    ) -> None:
        space = lattice_inclusion.codomain()
        match space.module_over_extension() is rational_group.rational_lattice():
            case False:
                raise ValueError("the integral structure must lie in the rational group's space")
            case True:
                pass
        match lattice_inclusion.domain().base_ring() is space.base_ring():
            case False:
                raise ValueError("the lattice and restricted rational space require one base ring")
            case True:
                pass
        self._rational_group = rational_group
        self._lattice_inclusion = lattice_inclusion

    def rational_group(self) -> RationalMatrixGroup:
        return self._rational_group

    def lattice_inclusion(self) -> ModuleEmbedding:
        """Return the selected lattice embedding ``L -> Res(V)``."""
        return self._lattice_inclusion

    @cached_property
    def _invariant_overlattice(self):
        current = self.lattice_inclusion()
        space = current.codomain()
        while True:
            current_basis = _embedded_basis(current)
            spanning = list(current_basis)
            for generator in self.rational_group().generators_and_inverses():
                spanning.extend(
                    space.wrap(generator(vector.underlying_element()))
                    for vector in current_basis
                )
            enlarged = _span_embedding(space, spanning)
            match _same_embedded_lattice(current, enlarged):
                case True:
                    return current
                case False:
                    current = enlarged

    def invariant_overlattice(self) -> ModuleEmbedding:
        """Return the smallest represented over-lattice stable under the generators.

        This is the source operation ``MatrixIntegral_GetInvariantSpace``:
        repeatedly take the ``ZZ``-span of the current lattice and all generator
        and inverse images.  No saturation is taken inside the divisible
        rational ambient space.
        """
        return self._invariant_overlattice

    @cached_property
    def _quotient_exponent(self):
        original = self.lattice_inclusion()
        invariant = self.invariant_overlattice()
        into_invariant = original.factor_through(invariant)
        return into_invariant.cokernel().exponent()

    def quotient_exponent(self):
        """Return the exponent of ``M/L`` for ``M`` the invariant over-lattice."""
        return self._quotient_exponent

    @cached_property
    def _scaling_morphism(self):
        from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
            module_homset,
        )

        invariant = self.invariant_overlattice().domain()
        modulus = self.quotient_exponent()
        return module_homset(invariant, invariant)(
            {
                label: invariant.scalar_multiple(modulus, invariant.module_generator(label))
                for label in invariant.module_generating_set()
            }
        )

    def finite_module(self):
        """Return ``F=M/dM`` as the actual cokernel of multiplication by ``d``."""
        return self._scaling_morphism.cokernel()

    def finite_projection(self):
        """Return the quotient map ``M -> M/dM``."""
        return self._scaling_morphism.cokernel_projection()

    def intermediate_image(self, lattice_inclusion: ModuleEmbedding):
        """Return ``L'/dM`` inside ``M/dM`` for ``dM <= L' <= M``."""
        invariant = self.invariant_overlattice()
        match lattice_inclusion.codomain() is invariant.codomain():
            case False:
                raise ValueError("an intermediate lattice lies in the selected rational space")
            case True:
                pass
        into_invariant = lattice_inclusion.factor_through(invariant)
        scaled_invariant = invariant * self._scaling_morphism
        scaled_invariant.factor_through(lattice_inclusion)
        return (self.finite_projection() * into_invariant).image()

    @cached_property
    def _selected_submodule(self):
        return self.intermediate_image(self.lattice_inclusion())

    def selected_submodule(self):
        """Return ``S=L/dM <= M/dM`` for the selected lattice."""
        return self._selected_submodule

    def _restricted_automorphism(self, automorphism: LatticeIsometry):
        invariant = self.invariant_overlattice()
        lattice = invariant.domain()
        space = invariant.codomain()
        return lattice.Aut()(
            {
                label: invariant.lift(
                    space.wrap(
                        automorphism(
                            invariant(lattice.module_generator(label)).underlying_element()
                        )
                    )
                )
                for label in lattice.module_generating_set()
            }
        )

    def _finite_automorphism(self, automorphism: LatticeIsometry):
        lattice = self.invariant_overlattice().domain()
        projection = self.finite_projection()
        restricted = self._restricted_automorphism(automorphism)
        quotient = self.finite_module()
        return quotient.Aut()(
            {
                label: projection(restricted(lattice.module_generator(label)))
                for label in lattice.module_generating_set()
            }
        )

    @cached_property
    def _finite_generators(self):
        return tuple(
            self._finite_automorphism(generator)
            for generator in self.rational_group().generators()
        )

    def _finite_generator_automorphisms(self):
        return self._finite_generators

    def _finite_generator_automorphisms_and_inverses(self):
        return self._finite_generators + tuple(~generator for generator in self._finite_generators)

    def preserves_selected_lattice(self, automorphism: LatticeIsometry) -> bool:
        """Return whether the selected rational isometry carries ``L`` onto itself."""
        inclusion = self.lattice_inclusion()
        space = inclusion.codomain()
        lattice = inclusion.domain()
        basis = tuple(
            inclusion(lattice.module_generator(label)).underlying_element()
            for label in lattice.module_generating_set()
        )
        inverse = ~automorphism
        return all(
            inclusion.is_in_image(space.wrap(automorphism(vector)))
            and inclusion.is_in_image(space.wrap(inverse(vector)))
            for vector in basis
        )

    @cached_property
    def _finite_representation(self) -> FiniteIntegralRepresentation:
        return FiniteIntegralRepresentation(self)

    def finite_representation(self) -> FiniteIntegralRepresentation:
        """Return the finite submodule-orbit representation controlling integrality."""
        return self._finite_representation

    def lattice_stabilizer(self) -> ArithmeticSubgroup:
        """Return ``{g in G : g(L)=L}`` from the finite representation."""
        return self.finite_representation().lattice_stabilizer()

    @staticmethod
    def _carries_lattice(
        automorphism: LatticeIsometry,
        source_inclusion: ModuleEmbedding,
        target_inclusion: ModuleEmbedding,
    ) -> bool:
        match source_inclusion.codomain() is target_inclusion.codomain():
            case False:
                return False
            case True:
                pass
        space = source_inclusion.codomain()
        source = source_inclusion.domain()
        target = target_inclusion.domain()
        inverse = ~automorphism
        source_basis = tuple(
            source_inclusion(source.module_generator(label)).underlying_element()
            for label in source.module_generating_set()
        )
        target_basis = tuple(
            target_inclusion(target.module_generator(label)).underlying_element()
            for label in target.module_generating_set()
        )
        return all(
            target_inclusion.is_in_image(space.wrap(automorphism(vector)))
            for vector in source_basis
        ) and all(
            source_inclusion.is_in_image(space.wrap(inverse(vector)))
            for vector in target_basis
        )

    def transporter(
        self,
        source_inclusion: ModuleEmbedding,
        target_inclusion: ModuleEmbedding,
    ) -> LatticeIsometry | None:
        """Return one ``g`` in the rational group with ``g(source)=target``.

        The finite submodule ``source/dM`` determines the source lattice among
        the intermediate lattices ``dM <= source <= M``.  An orbit witness in
        ``M/dM`` therefore lifts to a genuine lattice transporter, which is
        checked again on both actual embeddings before being returned.
        """
        source_action = IntegralStructureAction(self.rational_group(), source_inclusion)
        try:
            target_submodule = source_action.intermediate_image(target_inclusion)
        except ValueError:
            return None
        witness = source_action.finite_representation().transporter_to(target_submodule)
        match witness:
            case None:
                return None
            case _:
                pass
        match self._carries_lattice(witness, source_inclusion, target_inclusion):
            case False:
                raise ArithmeticError("a finite-module transporter does not carry the actual lattice")
            case True:
                return witness

    def right_cosets(self) -> RightCosetDecomposition:
        """Return the finite ``G/H`` decomposition for the selected stabilizer ``H``."""
        return self.finite_representation().right_cosets()

    def double_cosets(
        self,
        left_subgroup: ArithmeticSubgroup,
    ) -> DoubleCosetDecomposition:
        """Return ``left_subgroup \ G / G_L`` with all sides retained."""
        return self.finite_representation().double_cosets(left_subgroup)

    def double_cosets_from_generators(
        self,
        left_generators: tuple[LatticeIsometry, ...],
    ) -> DoubleCosetDecomposition:
        """Return ``V \ G / G_L`` for the subgroup generated by live ``V`` generators."""
        return self.double_cosets(
            ArithmeticSubgroup(self.rational_group(), tuple(left_generators))
        )

    def _repr_(self) -> str:
        return f"Integral-structure action of {self.rational_group()} on {self.lattice_inclusion().domain()}"


def integral_structure_action(rational_lattice: Lattice, generators, lattice_inclusion: ModuleEmbedding) -> IntegralStructureAction:
    """Build the T2 integral-structure action from live preamble objects."""
    return IntegralStructureAction(
        RationalMatrixGroup(rational_lattice, tuple(generators)),
        lattice_inclusion,
    )


__all__ = [
    "ArithmeticSubgroup",
    "DoubleCosetDecomposition",
    "DoubleCosetIntersection",
    "FiniteIntegralRepresentation",
    "IntegralStructureAction",
    "integral_structure_action",
    "RationalMatrixGroup",
    "RightCosetDecomposition",
]
