"""Integral structures for finitely generated rational isometry groups.

The public objects in this module retain preamble lattices, embeddings, and
isometries.  Sage matrices are used only privately to normalize a finite
``ZZ``-span inside a rational vector space.
"""

from __future__ import annotations

from functools import cached_property

from dzack_research.preamble.all import ZZ
from dzack_research.preamble.categories.lattice_morphisms import LatticeIsometry
from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
    ModuleEmbedding,
)
from dzack_research.preamble.categories.rings.ring_foundation import _engine_element
from dzack_research.preamble.lexicon.category_theory import ObjectOfCategory
from sage.libs.gap.libgap import libgap
from sage.matrix.constructor import matrix
from sage.rings.integer_ring import ZZ as SageZZ
from sage.rings.rational_field import QQ as SageQQ
from sage.structure.sage_object import SageObject


class RationalMatrixGroup(SageObject):
    """A finitely generated rational isometry group on one preamble lattice.

    The selected generators are actual elements of ``V.Aut()``.  No raw matrix
    is part of the public representation; matrix lowering belongs to private
    computation seams such as the finite integral-structure action below.
    """

    def __init__(
        self,
        rational_lattice: ObjectOfCategory,
        generators: tuple[LatticeIsometry, ...],
    ) -> None:
        selected = tuple(generators)
        automorphisms = rational_lattice.Aut()
        match any(generator.parent() is not automorphisms for generator in selected):
            case True:
                raise ValueError("rational-group generators must be automorphisms of one lattice")
            case False:
                pass
        self._rational_lattice = rational_lattice
        self._generators = selected

    def rational_lattice(self) -> ObjectOfCategory:
        """Return the rational lattice acted on by this group."""
        return self._rational_lattice

    def generators(self) -> tuple[LatticeIsometry, ...]:
        """Return the selected live isometry generators."""
        return self._generators

    def generators_and_inverses(self) -> tuple[LatticeIsometry, ...]:
        """Return the selected generators and their inverses."""
        return self._generators + tuple(~generator for generator in self._generators)

    def _repr_(self) -> str:
        return f"Rational isometry group on {self.rational_lattice()} generated by {len(self.generators())} elements"


def _embedded_basis(inclusion: ModuleEmbedding):
    domain = inclusion.domain()
    return tuple(inclusion(generator) for generator in domain.module_generators())


def _underlying_coordinates(space, element):
    ambient = space.module_over_extension()
    underlying = space(element).underlying_element()
    coefficients = ambient._framing_lift(underlying)
    base_ring = ambient.base_ring()
    return tuple(
        SageQQ(
            _engine_element(
                base_ring,
                coefficients(label),
            )
        )
        for label in ambient.module_generating_set()
    )


def _span_embedding(space, elements) -> ModuleEmbedding:
    """Return the exact ``ZZ``-span of finitely many elements of ``Res(V)``."""
    elements = tuple(elements)
    match elements:
        case ():
            raise ValueError("an integral lattice span requires at least one generator")
        case _:
            pass

    rows = tuple(_underlying_coordinates(space, element) for element in elements)
    denominator = SageZZ.one()
    for row in rows:
        for entry in row:
            denominator = denominator.lcm(entry.denominator())
    integral_rows = tuple(tuple(SageZZ(denominator * entry) for entry in row) for row in rows)
    integer_span = matrix(SageZZ, integral_rows).row_module()
    basis = integer_span.basis_matrix()

    ambient = space.module_over_extension()
    ambient_labels = tuple(ambient.module_generating_set())
    domain = ZZ.free_module(basis.nrows())

    def image(position):
        row = basis[int(position)]
        coefficients = {}
        for column, label in enumerate(ambient_labels):
            match row[column] == 0:
                case True:
                    pass
                case False:
                    coefficients[label] = ambient.base_ring()(int(row[column])) / ambient.base_ring()(int(denominator))
        return space.wrap(ambient.linear_combination(coefficients))

    return domain.Mono(space)(
        {label: image(label) for label in domain.module_generating_set()},
    )


class ArithmeticSubgroup(RationalMatrixGroup):
    """A generated arithmetic subgroup retaining its ambient rational group."""

    def __init__(
        self,
        supergroup: RationalMatrixGroup,
        generators: tuple[LatticeIsometry, ...],
    ) -> None:
        self._supergroup = supergroup
        super().__init__(supergroup.rational_lattice(), generators)

    def supergroup(self) -> RationalMatrixGroup:
        return self._supergroup


class RightCosetDecomposition(SageObject):
    """A finite decomposition ``G/H`` with the subgroup explicitly on the right."""

    def __init__(
        self,
        ambient_group: RationalMatrixGroup,
        right_subgroup: ArithmeticSubgroup,
        representatives: tuple[LatticeIsometry, ...],
    ) -> None:
        self._ambient_group = ambient_group
        self._right_subgroup = right_subgroup
        self._representatives = tuple(representatives)

    def ambient_group(self) -> RationalMatrixGroup:
        return self._ambient_group

    def right_subgroup(self) -> ArithmeticSubgroup:
        return self._right_subgroup

    def representatives(self) -> tuple[LatticeIsometry, ...]:
        return self._representatives

    def cardinality(self) -> int:
        return len(self._representatives)

    def _repr_(self) -> str:
        return f"Right-subgroup cosets {self.ambient_group()}/{self.right_subgroup()} with {self.cardinality()} representatives"


class DoubleCosetIntersection(SageObject):
    """Finite-image intersection data for one double coset ``V g H``."""

    def __init__(
        self,
        representative: LatticeIsometry,
        finite_image_order: int,
        double_coset_size: int,
    ) -> None:
        self._representative = representative
        self._finite_image_order = int(finite_image_order)
        self._double_coset_size = int(double_coset_size)

    def representative(self) -> LatticeIsometry:
        return self._representative

    def finite_image_order(self) -> int:
        return self._finite_image_order

    def double_coset_size(self) -> int:
        return self._double_coset_size


class DoubleCosetDecomposition(SageObject):
    r"""A finite decomposition ``V \ G / H`` retaining all three group sides."""

    def __init__(
        self,
        left_subgroup: ArithmeticSubgroup,
        ambient_group: RationalMatrixGroup,
        right_subgroup: ArithmeticSubgroup,
        representatives: tuple[LatticeIsometry, ...],
        intersections: tuple[DoubleCosetIntersection, ...],
        finite_ambient_order: int,
        finite_left_order: int,
        finite_right_order: int,
    ) -> None:
        self._left_subgroup = left_subgroup
        self._ambient_group = ambient_group
        self._right_subgroup = right_subgroup
        self._representatives = tuple(representatives)
        self._intersections = tuple(intersections)
        self._finite_ambient_order = int(finite_ambient_order)
        self._finite_left_order = int(finite_left_order)
        self._finite_right_order = int(finite_right_order)

    def left_subgroup(self) -> ArithmeticSubgroup:
        return self._left_subgroup

    def ambient_group(self) -> RationalMatrixGroup:
        return self._ambient_group

    def right_subgroup(self) -> ArithmeticSubgroup:
        return self._right_subgroup

    def representatives(self) -> tuple[LatticeIsometry, ...]:
        return self._representatives

    def intersections(self) -> tuple[DoubleCosetIntersection, ...]:
        return self._intersections

    def cardinality(self) -> int:
        return len(self._representatives)

    def finite_ambient_order(self) -> int:
        return self._finite_ambient_order

    def finite_left_order(self) -> int:
        return self._finite_left_order

    def finite_right_order(self) -> int:
        return self._finite_right_order

    def _repr_(self) -> str:
        return rf"Double cosets {self.left_subgroup()} \ {self.ambient_group()} / {self.right_subgroup()} with {self.cardinality()} representatives"


class FiniteIntegralRepresentation(SageObject):
    """The finite action controlling the integral structures in one commensurability class.

    The public orbit consists of actual submodules of ``M/dM``.  libGAP owns
    the private permutation group and subgroup preimage calculation; every
    resulting free-group word is evaluated back in the selected live rational
    isometries before it crosses the public boundary.
    """

    def __init__(self, action: IntegralStructureAction) -> None:
        self._action = action
        self._rational_permutation_cache = {}
        self._matrix_isometry_cache = {}
        (
            self._orbit_keys,
            self._orbit_witness_matrices,
            self._orbit_position_by_key,
        ) = self._compute_submodule_orbit()
        self._orbit = None
        self._orbit_witnesses = None
        self._generator_permutations = self._compute_generator_permutations()
        self._free_group = libgap.FreeGroup(len(action.rational_group().generators()))
        self._permutation_group = libgap.Group(list(self._generator_permutations))
        self._homomorphism = libgap.GroupHomomorphismByImages(
            self._free_group,
            self._permutation_group,
            self._free_group.GeneratorsOfGroup(),
            list(self._generator_permutations),
        )

    def action(self) -> IntegralStructureAction:
        return self._action

    def orbit(self):
        """Return the finite orbit of ``S=L/dM`` as represented submodules."""
        match self._orbit:
            case None:
                self._orbit = tuple(self._submodule_from_key(key) for key in self._orbit_keys)
            case _:
                pass
        return tuple(self._orbit)

    def orbit_witnesses(self) -> tuple[LatticeIsometry, ...]:
        """Return live rational isometries carrying ``S`` to the orbit members."""
        match self._orbit_witnesses:
            case None:
                automorphisms = self.action().rational_group().rational_lattice().Aut()
                self._orbit_witnesses = tuple(automorphisms._isometry_from_column_matrix(witness_matrix) for witness_matrix in self._orbit_witness_matrices)
            case _:
                pass
        return tuple(self._orbit_witnesses)

    def image_order(self) -> int:
        """Return the order of the finite permutation image."""
        return int(self._permutation_group.Size())

    @staticmethod
    def _row_lattice_key(rows) -> tuple[tuple[int, ...], ...]:
        basis = matrix(SageZZ, rows).row_module().basis_matrix()
        return tuple(tuple(int(entry) for entry in row) for row in basis.rows())

    @staticmethod
    def _submodule_key(submodule) -> tuple[tuple[int, ...], ...]:
        r"""Return the canonical integral preimage lattice of a finite submodule.

        For F = Z^n/R and S <= F generated by rows G, the inverse image of S
        in Z^n is R + <G>.  Its Hermite basis is therefore an exact equality
        key, without enumerating residue vectors.
        """
        inclusion = submodule.inclusion()
        ambient = inclusion.codomain()
        framing = ambient.framing_source()
        framing_labels = tuple(framing.module_generating_set())
        base_ring = framing.base_ring()

        def coordinates(element):
            vector = framing(element).to_vector()
            return tuple(SageZZ(_engine_element(base_ring, vector(label))) for label in framing_labels)

        presentation = ambient.presentation()
        rows = [coordinates(presentation(generator)) for generator in presentation.domain().module_generators()]
        augmentation = ambient.framing_morphism()
        rows.extend(coordinates(augmentation.lift(inclusion(generator))) for generator in inclusion.domain().module_generators())
        return FiniteIntegralRepresentation._row_lattice_key(rows)

    @staticmethod
    def _image_key(key, action_matrix) -> tuple[tuple[int, ...], ...]:
        moved = matrix(SageZZ, key) * action_matrix
        return FiniteIntegralRepresentation._row_lattice_key(moved.rows())

    def _submodule_from_key(self, key):
        invariant = self.action().invariant_overlattice().domain()
        invariant_labels = tuple(invariant.module_generating_set())
        source = ZZ.free_module(len(key))
        inclusion = source.Mono(invariant)(
            {
                label: invariant.linear_combination({invariant_labels[column]: ZZ(entry) for column, entry in enumerate(key[int(label)]) if entry})
                for label in source.module_generating_set()
            }
        )
        return (self.action().finite_projection() * inclusion).image()

    def _orbit_position(self, candidate) -> int | None:
        key = self._submodule_key(candidate)
        return self._orbit_position_by_key.get(key)

    @staticmethod
    def _image_submodule(automorphism, submodule):
        return (automorphism * submodule.inclusion()).image()

    def _compute_submodule_orbit(self):
        orbit_keys = [self._row_lattice_key(self.action()._selected_invariant_coordinates.rows())]
        orbit_position_by_key = {orbit_keys[0]: 0}
        witness_matrices = [self.action()._invariant_basis_matrix.parent().one()]
        steps = tuple(
            (
                self.action()._restricted_matrix(generator),
                self.action()._ambient_action_matrix(generator),
            )
            for generator in self.action().rational_group().generators()
        )
        frontier = [0]
        while frontier:
            source_position = frontier.pop()
            source_key = orbit_keys[source_position]
            source_witness_matrix = witness_matrices[source_position]
            for action_matrix, ambient_action_matrix in steps:
                candidate_key = self._image_key(source_key, action_matrix)
                if candidate_key not in orbit_position_by_key:
                    candidate_position = len(orbit_keys)
                    orbit_keys.append(candidate_key)
                    orbit_position_by_key[candidate_key] = candidate_position
                    witness_matrices.append(ambient_action_matrix * source_witness_matrix)
                    frontier.append(candidate_position)
        return orbit_keys, witness_matrices, orbit_position_by_key

    def _compute_generator_permutations(self):
        permutations = []
        for automorphism in self.action().rational_group().generators():
            action_matrix = self.action()._restricted_matrix(automorphism)
            images = []
            for key in self._orbit_keys:
                image_key = self._image_key(key, action_matrix)
                position = self._orbit_position_by_key.get(image_key)
                match position is None:
                    case True:
                        raise ArithmeticError("the finite-module generator left the computed orbit")
                    case False:
                        images.append(position + 1)
            permutations.append(libgap.PermList(images))
        return tuple(permutations)

    def _evaluate_free_word(self, word) -> LatticeIsometry:
        representation = tuple(int(entry) for entry in libgap.ExtRepOfObj(word).sage())
        generators = self.action().rational_group().generators()
        generator_matrices = tuple(self.action()._ambient_action_matrix(generator) for generator in generators)
        result = self.action()._invariant_basis_matrix.parent().one()
        for position in range(0, len(representation), 2):
            generator_matrix = generator_matrices[representation[position] - 1]
            exponent = representation[position + 1]
            result = (generator_matrix**exponent) * result
        matrix_key = tuple(tuple(entry for entry in row) for row in result.rows())
        cached = self._matrix_isometry_cache.get(matrix_key)
        match cached:
            case None:
                pass
            case _:
                return cached
        isometry = self.action().rational_group().rational_lattice().Aut()._isometry_from_column_matrix(result)
        self._matrix_isometry_cache[matrix_key] = isometry
        self.action()._ambient_action_matrix_cache[id(isometry)] = (isometry, result)
        return isometry

    @cached_property
    def _lattice_stabilizer(self) -> ArithmeticSubgroup:
        point_stabilizer = libgap.Stabilizer(self._permutation_group, 1)
        preimage = libgap.PreImage(self._homomorphism, point_stabilizer)
        lifted_by_identity = {}
        for word in preimage.GeneratorsOfGroup():
            isometry = self._evaluate_free_word(word)
            lifted_by_identity[id(isometry)] = isometry
        lifted = tuple(lifted_by_identity.values())
        match all(self.action().preserves_selected_lattice(generator) for generator in lifted):
            case False:
                raise ArithmeticError("a lifted finite stabilizer generator does not preserve the lattice")
            case True:
                pass
        return ArithmeticSubgroup(self.action().rational_group(), lifted)

    def lattice_stabilizer(self) -> ArithmeticSubgroup:
        """Return the exact preimage of the stabilizer of ``S=L/dM``."""
        return self._lattice_stabilizer

    def transporter_to(self, target_submodule):
        """Return a live rational isometry carrying ``S`` to ``target_submodule``."""
        position = self._orbit_position(target_submodule)
        match position:
            case None:
                return None
            case _:
                return self.orbit_witnesses()[position]

    @cached_property
    def _right_cosets(self) -> RightCosetDecomposition:
        return RightCosetDecomposition(
            self.action().rational_group(),
            self.lattice_stabilizer(),
            self.orbit_witnesses(),
        )

    def right_cosets(self) -> RightCosetDecomposition:
        """Return ``G/H`` where ``H`` is the selected lattice stabilizer."""
        return self._right_cosets

    def _permutation_of_rational_isometry(self, automorphism: LatticeIsometry):
        cached = self._rational_permutation_cache.get(id(automorphism))
        match cached is not None and cached[0] is automorphism:
            case True:
                return cached[1]
            case False:
                pass
        action_matrix = self.action()._restricted_matrix(automorphism)
        images = []
        for key in self._orbit_keys:
            image_key = self._image_key(key, action_matrix)
            position = self._orbit_position_by_key.get(image_key)
            match position is None:
                case True:
                    raise ArithmeticError("a rational subgroup generator leaves the finite orbit")
                case False:
                    images.append(position + 1)
        permutation = libgap.PermList(images)
        match permutation in self._permutation_group:
            case False:
                raise ValueError("the selected arithmetic subgroup is not contained in the ambient rational group")
            case True:
                self._rational_permutation_cache[id(automorphism)] = (
                    automorphism,
                    permutation,
                )
                return permutation

    def double_cosets(self, left_subgroup: ArithmeticSubgroup) -> DoubleCosetDecomposition:
        r"""Return ``left_subgroup \ G / H`` in the finite integral representation."""
        match left_subgroup.supergroup() is self.action().rational_group():
            case False:
                raise ValueError("a double-coset left subgroup must lie in the selected rational group")
            case True:
                pass
        left_image = libgap.Subgroup(
            self._permutation_group,
            [self._permutation_of_rational_isometry(generator) for generator in left_subgroup.generators()],
        )
        right_image = libgap.Stabilizer(self._permutation_group, 1)
        representatives = []
        intersections = []
        for double_coset in libgap.DoubleCosets(
            self._permutation_group,
            left_image,
            right_image,
        ):
            finite_representative = double_coset.Representative()
            word = libgap.PreImagesRepresentative(
                self._homomorphism,
                finite_representative,
            )
            match str(word) == "fail":
                case True:
                    raise ArithmeticError("a finite double-coset representative has no rational lift")
                case False:
                    pass
            representative = self._evaluate_free_word(word)
            double_coset_size = int(double_coset.Size())
            numerator = int(left_image.Size()) * int(right_image.Size())
            match numerator % double_coset_size:
                case 0:
                    intersection_order = numerator // double_coset_size
                case _:
                    raise ArithmeticError("the finite double-coset size violates the orbit-stabilizer formula")
            representatives.append(representative)
            intersections.append(
                DoubleCosetIntersection(
                    representative,
                    intersection_order,
                    double_coset_size,
                )
            )
        return DoubleCosetDecomposition(
            left_subgroup,
            self.action().rational_group(),
            self.lattice_stabilizer(),
            tuple(representatives),
            tuple(intersections),
            int(self._permutation_group.Size()),
            int(left_image.Size()),
            int(right_image.Size()),
        )


class IntegralStructureAction(SageObject):
    """A rational group acting on lattices commensurable with one selected lattice.

    ``lattice_inclusion`` is the actual monomorphism ``L -> Res_Z^Q(V)``.  The
    invariant-overlattice procedure has the explicit precondition from the
    source algorithm: the selected rational group stabilizes some lattice
    commensurable with ``L``.  Under that hypothesis the ascending sequence of
    finite ``ZZ``-spans stabilizes.
    """

    def __init__(
        self,
        rational_group: RationalMatrixGroup,
        lattice_inclusion: ModuleEmbedding,
    ) -> None:
        space = lattice_inclusion.codomain()
        match space.module_over_extension() is rational_group.rational_lattice():
            case False:
                raise ValueError("the integral structure must lie in the rational group's space")
            case True:
                pass
        match lattice_inclusion.domain().base_ring() is space.base_ring():
            case False:
                raise ValueError("the lattice and restricted rational space require one base ring")
            case True:
                pass
        self._rational_group = rational_group
        self._lattice_inclusion = lattice_inclusion
        self._ambient_action_matrix_cache = {}
        self._restricted_matrix_cache = {}

    def rational_group(self) -> RationalMatrixGroup:
        return self._rational_group

    def lattice_inclusion(self) -> ModuleEmbedding:
        """Return the selected lattice embedding ``L -> Res(V)``."""
        return self._lattice_inclusion

    def _ambient_action_matrix(self, automorphism: LatticeIsometry):
        cached = self._ambient_action_matrix_cache.get(id(automorphism))
        match cached is not None and cached[0] is automorphism:
            case True:
                return cached[1]
            case False:
                pass

        space = self.lattice_inclusion().codomain()
        ambient = space.module_over_extension()
        labels = tuple(ambient.module_generating_set())
        basis = tuple(ambient.module_generator(label) for label in labels)
        columns = tuple(
            _underlying_coordinates(
                space,
                space.wrap(automorphism(vector)),
            )
            for vector in basis
        )
        result = matrix(
            SageQQ,
            [[columns[column][row] for column in range(len(columns))] for row in range(len(labels))],
        )
        self._ambient_action_matrix_cache[id(automorphism)] = (automorphism, result)
        return result

    @cached_property
    def _invariant_overlattice(self):
        selected = self.lattice_inclusion()
        space = selected.codomain()
        ambient = space.module_over_extension()
        ambient_labels = tuple(ambient.module_generating_set())
        basis = matrix(
            SageQQ,
            tuple(_underlying_coordinates(space, element) for element in _embedded_basis(selected)),
        )
        match basis.nrows() == basis.ncols() and basis.rank() == basis.ncols():
            case False:
                raise ValueError("an integral structure must be a full-rank lattice in the selected rational space")
            case True:
                pass

        generator_matrices = tuple(self._ambient_action_matrix(generator) for generator in self.rational_group().generators())
        action_matrices = generator_matrices + tuple(action_matrix.inverse() for action_matrix in generator_matrices)

        changed = False
        while True:
            inverse_basis = basis.inverse()
            spanning_rows = list(basis.rows())
            stable = True
            for action_matrix in action_matrices:
                moved = basis * action_matrix.transpose()
                spanning_rows.extend(moved.rows())
                for row in moved.rows():
                    coordinates = row * inverse_basis
                    if any(entry.denominator() != 1 for entry in coordinates):
                        stable = False

            match stable:
                case True:
                    match changed:
                        case False:
                            return selected
                        case True:
                            elements = []
                            for row in basis.rows():
                                coefficients = {}
                                for column, label in enumerate(ambient_labels):
                                    entry = row[column]
                                    match entry == 0:
                                        case True:
                                            pass
                                        case False:
                                            coefficients[label] = ambient.base_ring()(int(entry.numerator())) / ambient.base_ring()(int(entry.denominator()))
                                elements.append(space.wrap(ambient.linear_combination(coefficients)))
                            return _span_embedding(space, elements)
                case False:
                    pass

            denominator = SageZZ.one()
            for row in spanning_rows:
                for entry in row:
                    denominator = denominator.lcm(entry.denominator())
            integral_rows = tuple(tuple(SageZZ(denominator * entry) for entry in row) for row in spanning_rows)
            integral_basis = matrix(SageZZ, integral_rows).row_module().basis_matrix()
            basis = matrix(
                SageQQ,
                [[SageQQ(entry) / SageQQ(denominator) for entry in row] for row in integral_basis.rows()],
            )
            changed = True

    def invariant_overlattice(self) -> ModuleEmbedding:
        """Return the smallest represented over-lattice stable under the generators.

        This is the source operation ``MatrixIntegral_GetInvariantSpace``:
        repeatedly take the ``ZZ``-span of the current lattice and all generator
        and inverse images.  No saturation is taken inside the divisible
        rational ambient space.
        """
        return self._invariant_overlattice

    @cached_property
    def _invariant_basis_matrix(self):
        space = self.invariant_overlattice().codomain()
        return matrix(
            SageQQ,
            tuple(_underlying_coordinates(space, element) for element in _embedded_basis(self.invariant_overlattice())),
        )

    @cached_property
    def _selected_invariant_coordinates(self):
        space = self.lattice_inclusion().codomain()
        selected_basis = matrix(
            SageQQ,
            tuple(_underlying_coordinates(space, element) for element in _embedded_basis(self.lattice_inclusion())),
        )
        coordinates = selected_basis * self._invariant_basis_matrix.inverse()
        match all(entry.denominator() == 1 for entry in coordinates.list()):
            case False:
                raise ArithmeticError("the selected lattice is not integral in its invariant over-lattice")
            case True:
                pass
        return matrix(
            SageZZ,
            [[SageZZ(entry) for entry in row] for row in coordinates.rows()],
        )

    @cached_property
    def _quotient_exponent(self):
        diagonal, _left, _right = self._selected_invariant_coordinates.smith_form()
        exponent = SageZZ.one()
        for entry in diagonal.diagonal():
            match entry:
                case 0:
                    raise ArithmeticError("the selected lattice must have finite index in its invariant over-lattice")
                case _:
                    exponent = exponent.lcm(abs(SageZZ(entry)))
        return ZZ(int(exponent))

    def quotient_exponent(self):
        """Return the exponent of ``M/L`` for ``M`` the invariant over-lattice."""
        return self._quotient_exponent

    @cached_property
    def _scaling_morphism(self):
        invariant = self.invariant_overlattice().domain()
        modulus = self.quotient_exponent()
        return invariant.Mor(invariant)({label: invariant.scalar_multiple(modulus, invariant.module_generator(label)) for label in invariant.module_generating_set()})

    def finite_module(self):
        """Return ``F=M/dM`` as the actual cokernel of multiplication by ``d``."""
        return self._scaling_morphism.cokernel()

    def finite_projection(self):
        """Return the quotient map ``M -> M/dM``."""
        return self._scaling_morphism.cokernel_projection()

    def intermediate_image(self, lattice_inclusion: ModuleEmbedding):
        """Return ``L'/dM`` inside ``M/dM`` for ``dM <= L' <= M``."""
        invariant = self.invariant_overlattice()
        match lattice_inclusion.codomain() is invariant.codomain():
            case False:
                raise ValueError("an intermediate lattice lies in the selected rational space")
            case True:
                pass
        into_invariant = lattice_inclusion.factor_through(invariant)
        scaled_invariant = invariant * self._scaling_morphism
        scaled_invariant.factor_through(lattice_inclusion)
        return (self.finite_projection() * into_invariant).image()

    @cached_property
    def _selected_submodule(self):
        return self.intermediate_image(self.lattice_inclusion())

    def selected_submodule(self):
        """Return ``S=L/dM <= M/dM`` for the selected lattice."""
        return self._selected_submodule

    def _restricted_matrix(self, automorphism: LatticeIsometry):
        cached = self._restricted_matrix_cache.get(id(automorphism))
        match cached is not None and cached[0] is automorphism:
            case True:
                return cached[1]
            case False:
                pass

        basis = self._invariant_basis_matrix
        moved = basis * self._ambient_action_matrix(automorphism).transpose()
        coordinates = moved * basis.inverse()
        match all(entry.denominator() == 1 for entry in coordinates.list()):
            case False:
                raise ArithmeticError("a rational-group generator does not preserve the computed invariant over-lattice")
            case True:
                pass
        result = matrix(
            SageZZ,
            [[SageZZ(entry) for entry in row] for row in coordinates.rows()],
        )
        self._restricted_matrix_cache[id(automorphism)] = (automorphism, result)
        return result

    def preserves_selected_lattice(self, automorphism: LatticeIsometry) -> bool:
        """Return whether the selected rational isometry carries ``L`` onto itself."""
        selected_key = FiniteIntegralRepresentation._row_lattice_key(self._selected_invariant_coordinates.rows())
        image_key = FiniteIntegralRepresentation._image_key(
            selected_key,
            self._restricted_matrix(automorphism),
        )
        return image_key == selected_key

    @cached_property
    def _finite_representation(self) -> FiniteIntegralRepresentation:
        return FiniteIntegralRepresentation(self)

    def finite_representation(self) -> FiniteIntegralRepresentation:
        """Return the finite submodule-orbit representation controlling integrality."""
        return self._finite_representation

    def lattice_stabilizer(self) -> ArithmeticSubgroup:
        """Return ``{g in G : g(L)=L}`` from the finite representation."""
        return self.finite_representation().lattice_stabilizer()

    def _carries_lattice(
        self,
        automorphism: LatticeIsometry,
        source_inclusion: ModuleEmbedding,
        target_inclusion: ModuleEmbedding,
    ) -> bool:
        match source_inclusion.codomain() is target_inclusion.codomain():
            case False:
                return False
            case True:
                pass
        space = source_inclusion.codomain()
        source_basis = matrix(
            SageQQ,
            tuple(_underlying_coordinates(space, element) for element in _embedded_basis(source_inclusion)),
        )
        target_basis = matrix(
            SageQQ,
            tuple(_underlying_coordinates(space, element) for element in _embedded_basis(target_inclusion)),
        )
        moved_basis = source_basis * self._ambient_action_matrix(automorphism).transpose()
        denominator = SageZZ.one()
        for entry in tuple(moved_basis.list()) + tuple(target_basis.list()):
            denominator = denominator.lcm(entry.denominator())
        moved_key = FiniteIntegralRepresentation._row_lattice_key(tuple(tuple(SageZZ(denominator * entry) for entry in row) for row in moved_basis.rows()))
        target_key = FiniteIntegralRepresentation._row_lattice_key(tuple(tuple(SageZZ(denominator * entry) for entry in row) for row in target_basis.rows()))
        return moved_key == target_key

    def transporter(
        self,
        source_inclusion: ModuleEmbedding,
        target_inclusion: ModuleEmbedding,
    ) -> LatticeIsometry | None:
        """Return one ``g`` in the rational group with ``g(source)=target``.

        The finite submodule ``source/dM`` determines the source lattice among
        the intermediate lattices ``dM <= source <= M``.  An orbit witness in
        ``M/dM`` therefore lifts to a genuine lattice transporter, which is
        checked again on both actual embeddings before being returned.
        """
        source_action = IntegralStructureAction(self.rational_group(), source_inclusion)
        try:
            target_submodule = source_action.intermediate_image(target_inclusion)
        except ValueError:
            return None
        witness = source_action.finite_representation().transporter_to(target_submodule)
        match witness:
            case None:
                return None
            case _:
                pass
        match self._carries_lattice(witness, source_inclusion, target_inclusion):
            case False:
                raise ArithmeticError("a finite-module transporter does not carry the actual lattice")
            case True:
                return witness

    def right_cosets(self) -> RightCosetDecomposition:
        """Return the finite ``G/H`` decomposition for the selected stabilizer ``H``."""
        return self.finite_representation().right_cosets()

    def double_cosets(
        self,
        left_subgroup: ArithmeticSubgroup,
    ) -> DoubleCosetDecomposition:
        r"""Return ``left_subgroup \ G / G_L`` with all sides retained."""
        return self.finite_representation().double_cosets(left_subgroup)

    def double_cosets_from_generators(
        self,
        left_generators: tuple[LatticeIsometry, ...],
    ) -> DoubleCosetDecomposition:
        r"""Return ``V \ G / G_L`` for the subgroup generated by live ``V`` generators."""
        return self.double_cosets(ArithmeticSubgroup(self.rational_group(), tuple(left_generators)))

    def _repr_(self) -> str:
        return f"Integral-structure action of {self.rational_group()} on {self.lattice_inclusion().domain()}"


def integral_structure_action(rational_lattice: ObjectOfCategory, generators, lattice_inclusion: ModuleEmbedding) -> IntegralStructureAction:
    """Build the T2 integral-structure action from live preamble objects."""
    return IntegralStructureAction(
        RationalMatrixGroup(rational_lattice, tuple(generators)),
        lattice_inclusion,
    )


def integral_structure_action_for_group(
    rational_group: RationalMatrixGroup,
    lattice_inclusion: ModuleEmbedding,
) -> IntegralStructureAction:
    """Build the T2 action while retaining the selected rational-group parent."""
    return IntegralStructureAction(rational_group, lattice_inclusion)


__all__ = [
    "ArithmeticSubgroup",
    "DoubleCosetDecomposition",
    "DoubleCosetIntersection",
    "FiniteIntegralRepresentation",
    "IntegralStructureAction",
    "integral_structure_action",
    "integral_structure_action_for_group",
    "RationalMatrixGroup",
    "RightCosetDecomposition",
]
